name: Deploy PHP Application via SFTP

on:
  push:
    branches:
      - main # Adjust this to match the branches you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          SECRETS="${{ secrets.ENV_STAGING }}"
          echo "$SECRETS" | tr ';' '\n' >> .env

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, xml, pdo_mysql, mysqli, gd, imagick, redis # Add any other extensions you need
          tools: composer:v2 # Specify Composer version if necessary

      - name: Install Composer dependencies
        run: composer install --ignore-platform-reqs

      - name: Install SSH Client
        run: sudo apt-get install openssh-client

      - name: Upload files via SFTP
        run: |
          sftp -oPort=${{ secrets.SFTP_PORT }} -o StrictHostKeyChecking=no ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_SERVER }} <<EOF
          cd /home/garudanu/api-staging.garudanusa.id/
          put -r ./*
          bye
          EOF
        env:
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
